### ISSUE TITLE
[BUG] Problems when update Open WebUI

### ISSUE THREAD

**Issue by Pelirrojo** [evereven-tech/horizons-omnichat#11]
## Describe the bug
Solution is not able to start

## To Reproduce
1. Change Open Web UI version
2. make hybrid-up
fails

## Expected behavior
Run normally

## Environment
- Deployment Mode: Hybrid
- OS: Ubuntu@24
- Version: v0.3.2-ecs

## Logs
Appears error in container logs about filesystem not ready or busy.

**Comment by Pelirrojo** [comment]
With the solution stopped:

1. Edit manually the file: hybrid/docker-compose.yaml to comment and uncomment lines: 43 & 44
```yaml
  open-webui:
    container_name: open-webui
   ...
    volumes:
      - ./tmp/:/app/backend/data/                                  # Useful for blocking updates            <==== Uncomment this line
      #- ./config.json:/app/backend/data/config.json                                                                  <==== Comment this line
```

2. Run the solution normally
3. when finish your session, stop the solution and undo step 1.

This workaround allows the update to finish quietly by giving enough space on filesystem to generate temporary files (i.e. config_old.json file) and when the update is finished, this file is not needed so going back to mount only the config file it's enough.
